name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^0.7.0
  animated_text_kit: ^1.3.1
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  modal_progress_hud: ^0.1.3
  flutter_svg: ^0.14.3
  google_sign_in: ^4.0.11
  #cached_network_image: ^1.1.3
  cupertino_icons: ^0.1.2
  timeago: ^2.0.21


  camera: ^0.5.6+3
  #camera: ^0.2.6

  path_provider: ^0.4.1
  video_player: ^0.7.2
  #image_picker: ^0.4.10
  http: ^0.12.0+2



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/ic_flutter_devs_logo.png
    - images/ic_powered_by.png
    - images/ic_switch_camera_3.png
    - images/ic_no_video.png
    - images/ic_play.png
    - images/ic_stop_video.png
    - images/ic_video_shutter.png
    - images/white.jpg
    - images/
